#############################################################################
# Makefile for building: ithome
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ?? 15 14:13:22 2014
# Project:  ithome.pro
# Template: app
# Command: f:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe -spec ..\..\qtsdk\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf ithome.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = f:\qtsdk\symbian\sdks\symbian3qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/include/QtCore"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/include/QtNetwork"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/include/QtGui"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/include/QtXml"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/include/QtWebKit"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/include/QtDeclarative"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/include"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/mkspecs/common/symbian"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/sys"  -I"F:/ithome/trunk/qmlapplicationviewer"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/mw"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/loc/sc"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/platform/mw/loc/sc"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/include/stdapis/stlportv5"  -I"F:/qtsdk/Symbian/SDKs/Symbian3Qt474/include/QtXmlPatterns"  -I"F:/ithome/trunk/moc"  -I"F:/ithome/trunk/src"  -I"F:/ithome/trunk"  -I"F:/ithome/trunk/rcc"  -I"F:/ithome/trunk/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "F:/ithome/trunk/ithome.pro"  -spec ..\..\qtsdk\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: F:/ithome/trunk/ithome.pro
	$(QMAKE) "F:/ithome/trunk/ithome.pro"  -spec ..\..\qtsdk\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

f:\ithome\trunk\ithome.loc: 
	$(QMAKE) "F:/ithome/trunk/ithome.pro"  -spec ..\..\qtsdk\Symbian\SDKs\Symbian3Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: f:\ithome\trunk\ithome.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call f:/qtsdk/Symbian/SDKs/Symbian3Qt474/epoc32/release/winscw/udeb/ithome.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis ithome.sis ithome.exe $(QT_RUN_OPTIONS)

ithome_template.pkg: F:/ithome/trunk/ithome.pro
	$(MAKE) -f $(MAKEFILE) qmake

ithome_installer.pkg: F:/ithome/trunk/ithome.pro
	$(MAKE) -f $(MAKEFILE) qmake

ithome_stub.pkg: F:/ithome/trunk/ithome.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: ithome_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) ithome_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: ithome_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o ithome_template.pkg $(QT_SIS_TARGET)

ithome.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: ithome_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: ithome_installer.pkg
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) ithome_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: ithome_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: ithome_installer.pkg
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o ithome_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: ithome_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) ithome_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call ithome.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_qmlapplicationviewer.cpp moc\moc_settings.cpp moc\moc_utility.cpp moc\moc_threaddownloadimage.cpp moc\moc_myxmllistmodel.cpp moc\moc_cache.cpp moc\moc_mynetworkaccessmanagerfactory.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_qmlapplicationviewer.cpp moc\moc_settings.cpp moc\moc_utility.cpp moc\moc_threaddownloadimage.cpp moc\moc_myxmllistmodel.cpp moc\moc_cache.cpp moc\moc_mynetworkaccessmanagerfactory.cpp
moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN f:\ithome\trunk\qmlapplicationviewer\qmlapplicationviewer.h -o f:\ithome\trunk\moc\moc_qmlapplicationviewer.cpp

moc\moc_settings.cpp: src\settings.h
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN f:\ithome\trunk\src\settings.h -o f:\ithome\trunk\moc\moc_settings.cpp

moc\moc_utility.cpp: src\settings.h \
		src\utility.h
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN f:\ithome\trunk\src\utility.h -o f:\ithome\trunk\moc\moc_utility.cpp

moc\moc_threaddownloadimage.cpp: src\settings.h \
		src\threaddownloadimage.h
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN f:\ithome\trunk\src\threaddownloadimage.h -o f:\ithome\trunk\moc\moc_threaddownloadimage.cpp

moc\moc_myxmllistmodel.cpp: src\myxmllistmodel.h
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN f:\ithome\trunk\src\myxmllistmodel.h -o f:\ithome\trunk\moc\moc_myxmllistmodel.cpp

moc\moc_cache.cpp: src\settings.h \
		src\threaddownloadimage.h \
		src\cache.h
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN f:\ithome\trunk\src\cache.h -o f:\ithome\trunk\moc\moc_cache.cpp

moc\moc_mynetworkaccessmanagerfactory.cpp: src\mynetworkaccessmanagerfactory.h
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN f:\ithome\trunk\src\mynetworkaccessmanagerfactory.h -o f:\ithome\trunk\moc\moc_mynetworkaccessmanagerfactory.cpp

compiler_rcc_make_all: rcc\qrc_symbian.cpp rcc\qrc_general.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc\qrc_symbian.cpp rcc\qrc_general.cpp
rcc\qrc_symbian.cpp: symbian.qrc \
		Image\back2.svg \
		Image\comment2.svg \
		Image\about_symbian.svg \
		Image\edit.svg \
		Image\about_inverse_symbian.svg \
		Image\to_down_inverse_symbian.svg \
		Image\toolbar_inverse.svg \
		Image\slider-3.png \
		Image\message_send_inverted.svg \
		Image\search2.svg \
		Image\ithome.svg \
		Image\to_up_inverse_symbian.svg \
		Image\to_up_symbian.svg \
		Image\slider-2.png \
		Image\edit2.svg \
		Image\qgn_indi_browser_tb_zoom_in.svg \
		Image\Symbian.png \
		Image\message_send.svg \
		Image\userCenter_symbian.svg \
		Image\to_down_symbian.svg \
		Image\toolbar.svg \
		Image\back.svg \
		Image\search.svg \
		Image\toolbar-delete_inverse.svg \
		Image\qgn_indi_browser_tb_zoom_out.svg \
		Image\slider-1.png \
		Image\setting2.svg \
		Image\refresh.svg \
		Image\share.svg \
		Image\share2.svg \
		Image\comment.svg \
		Image\setting.svg \
		Image\refresh2.svg \
		Image\userCenter_symbian_inverse.svg
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\rcc.exe -name symbian f:\ithome\trunk\symbian.qrc -o f:\ithome\trunk\rcc\qrc_symbian.cpp

rcc\qrc_general.cpp: general.qrc \
		Image\04.png \
		Image\icon_grade_middle_star_s.png \
		Image\shade_symbian.svg \
		Image\PageHeader.svg \
		Image\ithome_logo.png \
		Image\save.svg \
		Image\01.png \
		Image\shadow.png \
		Image\up.svg \
		Image\shade_inverse_symbian.svg \
		Image\it.png \
		Image\Sina_Weibo.svg \
		Image\02.png \
		Image\Qzone.svg \
		Image\Copy.svg \
		Image\tencent_Weibo.svg \
		Image\yiyue.png \
		Image\ist_indicator.svg \
		Image\03.png \
		Image\pull_down_inverse.svg \
		Image\Browser.svg \
		Image\tieba.svg \
		Image\icon_grade_middle_star_n.png \
		Image\pull_down.svg
	f:\qtsdk\Symbian\SDKs\Symbian3Qt474\bin\rcc.exe -name general f:\ithome\trunk\general.qrc -o f:\ithome\trunk\rcc\qrc_general.cpp

compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

dodistclean:
	-@ if EXIST "f:\ithome\trunk\ithome_template.pkg" $(DEL_FILE)  "f:\ithome\trunk\ithome_template.pkg"
	-@ if EXIST "f:\ithome\trunk\ithome_stub.pkg" $(DEL_FILE)  "f:\ithome\trunk\ithome_stub.pkg"
	-@ if EXIST "f:\ithome\trunk\ithome_installer.pkg" $(DEL_FILE)  "f:\ithome\trunk\ithome_installer.pkg"
	-@ if EXIST "f:\ithome\trunk\Makefile" $(DEL_FILE)  "f:\ithome\trunk\Makefile"
	-@ if EXIST "f:\ithome\trunk\ithome_exe.mmp" $(DEL_FILE)  "f:\ithome\trunk\ithome_exe.mmp"
	-@ if EXIST "f:\ithome\trunk\ithome_reg.rss" $(DEL_FILE)  "f:\ithome\trunk\ithome_reg.rss"
	-@ if EXIST "f:\ithome\trunk\ithome.rss" $(DEL_FILE)  "f:\ithome\trunk\ithome.rss"
	-@ if EXIST "f:\ithome\trunk\ithome.loc" $(DEL_FILE)  "f:\ithome\trunk\ithome.loc"
	-@ if EXIST "f:\ithome\trunk\bld.inf" $(DEL_FILE)  "f:\ithome\trunk\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


