#############################################################################
# Makefile for building: ithome
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? ?? 13 18:21:04 2014
# Project:  ithome.pro
# Template: app
# Command: f:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe -spec ../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile ithome.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQ_OS_HARMATTAN -DHARMATTAN_BOOSTER -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_WEBKIT_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/applauncherd -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/applauncherd -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -I. -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtCore -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtNetwork -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtGui -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtXml -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtWebKit -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtDeclarative -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtSystemInfo -Iqmlapplicationviewer -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4 -I../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/include/qt4/QtMobility -Imoc
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,F:/usr/lib
LIBS          = $(SUBLIBS)  -Lf:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib -pie -rdynamic -lmdeclarativecache -L/usr/lib -lQtSystemInfo -lQtDeclarative -lQtWebKit -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = f:/qtsdk/madde/targets/harmattan_10.2011.34-1_rt1.2/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		src/settings.cpp \
		src/utility.cpp \
		src/threaddownloadimage.cpp \
		src/myxmllistmodel.cpp \
		src/cache.cpp \
		qmlapplicationviewer/qmlapplicationviewer.cpp moc/moc_qmlapplicationviewer.cpp \
		moc/moc_settings.cpp \
		moc/moc_utility.cpp \
		moc/moc_threaddownloadimage.cpp \
		moc/moc_myxmllistmodel.cpp \
		moc/moc_cache.cpp \
		rcc/qrc_meego.cpp \
		rcc/qrc_general.cpp
OBJECTS       = obj/main.o \
		obj/settings.o \
		obj/utility.o \
		obj/threaddownloadimage.o \
		obj/myxmllistmodel.o \
		obj/cache.o \
		obj/qmlapplicationviewer.o \
		obj/moc_qmlapplicationviewer.o \
		obj/moc_settings.o \
		obj/moc_utility.o \
		obj/moc_threaddownloadimage.o \
		obj/moc_myxmllistmodel.o \
		obj/moc_cache.o \
		obj/qrc_meego.o \
		obj/qrc_general.o
DIST          = ../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		ithome.pro
QMAKE_TARGET  = ithome
DESTDIR       = 
TARGET        = ithome

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ithome.pro  ../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default/qmake.conf ../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		qmlapplicationviewer/qmlapplicationviewer.pri \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf \
		../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf \
		f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl \
		f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtWebKit.prl \
		f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtXml.prl \
		f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl \
		f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl \
		f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec ../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile ithome.pro
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/g++.conf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/unix.conf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/common/linux.conf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/qconfig.pri:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt_config.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_pre.prf:
qmlapplicationviewer/qmlapplicationviewer.pri:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/release.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/default_post.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/mobility.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/warn_on.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/qt.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/moc.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/resources.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/uic.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/yacc.prf:
../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/features/lex.prf:
f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtDeclarative.prl:
f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtWebKit.prl:
f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtXml.prl:
f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtGui.prl:
f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtNetwork.prl:
f:/qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../qtsdk/Madde/sysroots/harmattan_sysroot_10.2011.34-1_slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile ithome.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/ithome1.1.4 || $(MKDIR) obj/ithome1.1.4 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/ithome1.1.4/ && $(COPY_FILE) --parents qmlapplicationviewer/qmlapplicationviewer.h src/settings.h src/utility.h src/threaddownloadimage.h src/myxmllistmodel.h src/cache.h obj/ithome1.1.4/ && $(COPY_FILE) --parents meego.qrc general.qrc obj/ithome1.1.4/ && $(COPY_FILE) --parents main.cpp src/settings.cpp src/utility.cpp src/threaddownloadimage.cpp src/myxmllistmodel.cpp src/cache.cpp qmlapplicationviewer/qmlapplicationviewer.cpp obj/ithome1.1.4/ && (cd `dirname obj/ithome1.1.4` && $(TAR) ithome1.1.4.tar ithome1.1.4 && $(COMPRESS) ithome1.1.4.tar) && $(MOVE) `dirname obj/ithome1.1.4`/ithome1.1.4.tar.gz . && $(DEL_FILE) -r obj/ithome1.1.4


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_qmlapplicationviewer.cpp moc/moc_settings.cpp moc/moc_utility.cpp moc/moc_threaddownloadimage.cpp moc/moc_myxmllistmodel.cpp moc/moc_cache.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_qmlapplicationviewer.cpp moc/moc_settings.cpp moc/moc_utility.cpp moc/moc_threaddownloadimage.cpp moc/moc_myxmllistmodel.cpp moc/moc_cache.cpp
moc/moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	f:/qtsdk/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) qmlapplicationviewer/qmlapplicationviewer.h -o moc/moc_qmlapplicationviewer.cpp

moc/moc_settings.cpp: src/settings.h
	f:/qtsdk/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/settings.h -o moc/moc_settings.cpp

moc/moc_utility.cpp: src/utility.h
	f:/qtsdk/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/utility.h -o moc/moc_utility.cpp

moc/moc_threaddownloadimage.cpp: src/settings.h \
		src/threaddownloadimage.h
	f:/qtsdk/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/threaddownloadimage.h -o moc/moc_threaddownloadimage.cpp

moc/moc_myxmllistmodel.cpp: src/myxmllistmodel.h
	f:/qtsdk/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/myxmllistmodel.h -o moc/moc_myxmllistmodel.cpp

moc/moc_cache.cpp: src/settings.h \
		src/threaddownloadimage.h \
		src/cache.h
	f:/qtsdk/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/moc.exe $(DEFINES) $(INCPATH) src/cache.h -o moc/moc_cache.cpp

compiler_rcc_make_all: rcc/qrc_meego.cpp rcc/qrc_general.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_meego.cpp rcc/qrc_general.cpp
rcc/qrc_meego.cpp: meego.qrc \
		Image/comment_meego.svg \
		Image/comment2_meego.svg \
		Image/about_meego.png \
		Image/to_up_inverse_meego.png \
		Image/to_down_meego.png \
		Image/skin_invert.png \
		Image/skin.png \
		Image/to_down_inverse_meego.png \
		Image/to_up_meego.png \
		Image/about_inverse_meego.png
	f:/qtsdk/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/rcc.exe -name meego meego.qrc -o rcc/qrc_meego.cpp

rcc/qrc_general.cpp: general.qrc \
		Image/04.png \
		Image/icon_grade_middle_star_s.png \
		Image/PageHeader.svg \
		Image/ithome_logo.png \
		Image/save.svg \
		Image/01.png \
		Image/shadow.png \
		Image/up.svg \
		Image/it.png \
		Image/Sina_Weibo.svg \
		Image/02.png \
		Image/Qzone.svg \
		Image/Copy.svg \
		Image/tencent_Weibo.svg \
		Image/yiyue.png \
		Image/ist_indicator.svg \
		Image/03.png \
		Image/pull_down_inverse.svg \
		Image/Browser.svg \
		Image/tieba.svg \
		Image/icon_grade_middle_star_n.png \
		Image/pull_down.svg
	f:/qtsdk/Madde/targets/harmattan_10.2011.34-1_rt1.2/bin/rcc.exe -name general general.qrc -o rcc/qrc_general.cpp

compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

obj/main.o: main.cpp src/cache.h \
		src/settings.h \
		src/threaddownloadimage.h \
		src/utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/settings.o: src/settings.cpp src/settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/settings.o src/settings.cpp

obj/utility.o: src/utility.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/utility.o src/utility.cpp

obj/threaddownloadimage.o: src/threaddownloadimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/threaddownloadimage.o src/threaddownloadimage.cpp

obj/myxmllistmodel.o: src/myxmllistmodel.cpp src/myxmllistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/myxmllistmodel.o src/myxmllistmodel.cpp

obj/cache.o: src/cache.cpp src/cache.h \
		src/settings.h \
		src/threaddownloadimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cache.o src/cache.cpp

obj/qmlapplicationviewer.o: qmlapplicationviewer/qmlapplicationviewer.cpp qmlapplicationviewer/qmlapplicationviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qmlapplicationviewer.o qmlapplicationviewer/qmlapplicationviewer.cpp

obj/moc_qmlapplicationviewer.o: moc/moc_qmlapplicationviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_qmlapplicationviewer.o moc/moc_qmlapplicationviewer.cpp

obj/moc_settings.o: moc/moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_settings.o moc/moc_settings.cpp

obj/moc_utility.o: moc/moc_utility.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_utility.o moc/moc_utility.cpp

obj/moc_threaddownloadimage.o: moc/moc_threaddownloadimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_threaddownloadimage.o moc/moc_threaddownloadimage.cpp

obj/moc_myxmllistmodel.o: moc/moc_myxmllistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_myxmllistmodel.o moc/moc_myxmllistmodel.cpp

obj/moc_cache.o: moc/moc_cache.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_cache.o moc/moc_cache.cpp

obj/qrc_meego.o: rcc/qrc_meego.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_meego.o rcc/qrc_meego.cpp

obj/qrc_general.o: rcc/qrc_general.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_general.o rcc/qrc_general.cpp

####### Install

install_splash: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/ithome/data/ || $(MKDIR) $(INSTALL_ROOT)/opt/ithome/data/ 
	-$(INSTALL_FILE) f:/ithome/trunk/Image/MeeGo.png $(INSTALL_ROOT)/opt/ithome/data/


uninstall_splash:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ithome/data/MeeGo.png
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ithome/data/ 


install_iconsvg: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/ 
	-$(INSTALL_FILE) f:/ithome/trunk/ithomemeego.svg $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/


uninstall_iconsvg:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/ithomemeego.svg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/themes/base/meegotouch/ithome/ 


install_itemfolder_03: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/ithome/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/ithome/qml/ 
	-$(INSTALL_DIR) f:/ithome/trunk/qml/general $(INSTALL_ROOT)/opt/ithome/qml/


uninstall_itemfolder_03:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ithome/qml/general
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ithome/qml/ 


install_itemfolder_01: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/ithome/qml/ || $(MKDIR) $(INSTALL_ROOT)/opt/ithome/qml/ 
	-$(INSTALL_DIR) f:/ithome/trunk/qml/meego $(INSTALL_ROOT)/opt/ithome/qml/


uninstall_itemfolder_01:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ithome/qml/meego
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ithome/qml/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 
	-$(INSTALL_FILE) f:/ithome/trunk/ithome80.png $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ithome80.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/80x80/apps/ 


install_desktopfile: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) f:/ithome/trunk/ithome_harmattan.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/ithome_harmattan.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/ithome/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/ithome/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/ithome/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/ithome/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ithome/bin/ 


install:  install_splash install_iconsvg install_itemfolder_03 install_itemfolder_01 install_icon install_desktopfile install_target  FORCE

uninstall: uninstall_splash uninstall_iconsvg uninstall_itemfolder_03 uninstall_itemfolder_01 uninstall_icon uninstall_desktopfile uninstall_target   FORCE

FORCE:

